<a href="https://colab.research.google.com/github/phospeyt/Linear-Algebra_Second-Sem/blob/main/Assignment6_POLICARPIO%2CFAITH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition


In Python, transposing a matrix is a trivial task. Matrix transpose is simply an inverted version of the real matrix. We can obtain the transpose of any matrix by swapping the rows and columns. The row's items are converted to columns, and the columns' items are converted to rows. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [2]:
A = np.array([
    [7 ,5, 6],
    [2, -1, 0],
    [1, -4, 8]
])
A

array([[ 7,  5,  6],
       [ 2, -1,  0],
       [ 1, -4,  8]])

In [3]:
AT1 = np.transpose(A)
AT1


array([[ 7,  2,  1],
       [ 5, -1, -4],
       [ 6,  0,  8]])

In [4]:
AT2 = A.T
AT2

array([[ 7,  2,  1],
       [ 5, -1, -4],
       [ 6,  0,  8]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [3,8,3,9],
    [6,0,2,7],
])
B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [8]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [9]:
F = np.array([
    [42 ,45, 26],
    [30, -93, 52],
    [52, -26, 17]
])
F

array([[ 42,  45,  26],
       [ 30, -93,  52],
       [ 52, -26,  17]])

In [10]:
FT1 = np.transpose(F)

In [11]:
FT2 = F.T

In [12]:
np.array_equiv(FT1, FT2)

True

In [13]:
L = np.array([
    [2,8,6,4],
    [0,4,5,9],
    [3,6,9,2]
])
L.shape

(3, 4)

In [14]:
np.transpose(L).shape

(4, 3)

In [15]:
L.T.shape

(4, 3)

## Dot Product / Inner Product


The dot product, alternatively called the scalar product, is a mathematical operation that takes two equal-length sequences of numbers and returns a single number. Given two vectors A and B, we must find their dot product.

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [21]:
X = np.array([
    [31,42],
    [40,12]
])
Y = np.array([
    [-13,30],
    [52,22]
])

In [22]:
np.dot(X,Y)

array([[1781, 1854],
       [ 104, 1464]])

In [23]:
X.dot(Y)

array([[1781, 1854],
       [ 104, 1464]])

In [24]:
X @ Y

array([[1781, 1854],
       [ 104, 1464]])

In [25]:
np.matmul(X,Y)

array([[1781, 1854],
       [ 104, 1464]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [29]:
A = np.array([
    [51, 24],
    [49, -12],
    [61, 31]
])
B = np.array([
    [10,12],
    [35,31],
    [-31,-72]
])
T = np.array([
    [20,16,11],
    [81,41,22]
])
print(A.shape)
print(B.shape)
print(T.shape)

(3, 2)
(3, 2)
(2, 3)


In [30]:
A @ T

array([[2964, 1800, 1089],
       [   8,  292,  275],
       [3731, 2247, 1353]])

In [31]:
B @ T

array([[ 1172,   652,   374],
       [ 3211,  1831,  1067],
       [-6452, -3448, -1925]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [32]:
A @ B.T

array([[  798,  2529, -3309],
       [  346,  1343,  -655],
       [  982,  3096, -4123]])

In [33]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [34]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [35]:
A = np.array([
    [32,12,21],
    [43,15,12],
    [91,11,50]
])
B = np.array([
    [41,41,16],
    [94,51,19],
    [61,34,28]
])
C = np.array([
    [19,71,50],
    [70,51,11],
    [11,20,71]
])

In [36]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.array_equal(a_dot_z,z_mat)

True

In [40]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

#### In linear algebra, the determinant is a very significant value. The determinant of a square matrix is a specific number that may be derived from a square matrix and is denoted by the symbol. A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [42]:
A = np.array([
    [4,2],
    [9,5]
])
np.linalg.det(A)

2.000000000000001

In [45]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,4,9,3],
    [0,7,1,5],
    [3,2,8,1],
    [9,0,6,8]
])
np.linalg.det(B)

-795.0000000000001

## Inverse

The inverse of a matrix is simply the reciprocal of the matrix, as we do in standard arithmetic when dealing with a single number. This reciprocal is used to solve equations and determine the values of unknown variables. The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [46]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [47]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [48]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [51]:
np.array([])

array([], dtype=float64)

1. $A \cdot B \neq B \cdot A$

In [57]:
A = np.array([
        [15,47,13], 
        [44 ,51,62], 
        [71 ,28,19]
        ])
B = np.array([
        [57,98,19], 
        [48,46,14],
        [76,38,19]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += A[i][k] * B[k][j] 

print('A.B IS')
print(result)

A = np.array([
        [15,47,13], 
        [44 ,51,62], 
        [71 ,28,19]
        ])
B = np.array([
        [57,98,19], 
        [48,46,14],
        [76,38,19]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print('B.A IS')
print(result)
print('Therefore A.B is not equalt to B.A')


A.B IS
[[4099, 4126, 1190], [9668, 9014, 2728], [6835, 8968, 2102]]
B.A IS
[[539, 611, 690], [607, 374, 189], [548, 628, 714]]
Therefore A.B is not equalt to B.A


2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [59]:
A = np.array ([
      [31, 12, 63],
      [46, 43, 16],
      [17, 58, 29]
      ])
B = np.array ([
      [15, 12, 35],
      [44, 52, 26],
      [74, 18, 91]
      ])
C = np.array ([
      [1, 22, 32],
      [42, 15, 56],
      [71, 35, 29]
      ])


result = np.dot(B,C)
result = np.dot(A,result);
print("A.(B.C) is")
for r in result:
 print(r)
result = np.dot(A,B)
result = np.dot(result,C);
print("(A.B).C) is")
for r in result:
 print(r)


A.(B.C) is
[601345 405910 507010]
[430022 275432 414104]
[498799 331066 505566]
(A.B).C) is
[601345 405910 507010]
[430022 275432 414104]
[498799 331066 505566]


 3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [60]:
A = np.array ([
      [21, 22, 43],
      [74, 15, 63],
      [17, 81, 59]
      ])
B = np.array ([
      [55, 44, 93],
      [4, 79, 26],
      [74, 83, 91]
      ])
C = np.array ([
      [19, 32, 44],
      [41, 53, 66],
      [76, 28, 49]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(A,result)
print("A.(B+C) is")
for r in result:
 print(r)
result = np.dot(A,B)
result1 = np.dot(A,C)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("A.B+A.C) is")
for r in result:
 print(r)


A.(B+C) is
[ 8994  9273 10921]
[15601 14597 20338]
[13753 18533 18041]
A.B+A.C) is
[8994, 9273, 10921]
[15601, 14597, 20338]
[13753, 18533, 18041]


4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [61]:
A = np.array ([
      [81, 42, 33],
      [42, 52, 64],
      [17, 38, 91]
      ])
B = np.array ([
      [12, 42, 23],
      [41, 65, 56],
      [47, 18, 91]
      ])
C = np.array ([
      [14, 26, 13],
      [41, 25, 36],
      [75, 48, 59]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(result,A)
print("A.(B+C) is")
for r in result:
 print(r)
result = np.dot(B,A)
result1 = np.dot(C,A)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("(A.B)+(A.C) is")
for r in result:
 print(r)

A.(B+C) is
[5574 5996 8486]
[11986 11620 16838]
[15204 14256 21900]
(A.B)+(A.C) is
[5574, 5996, 8486]
[11986, 11620, 16838]
[15204, 14256, 21900]


 5. $A\cdot I = A$

In [70]:
A = np.array([
        [72,17,23], 
        [44 ,54,46], 
        [72 ,8,69]
        ])
B = np.array([
        [1,0,0], 
        [0,1,0],
        [0,0,1]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print (result)


[[72, 17, 23], [44, 54, 46], [72, 8, 69]]


 6. $A\cdot \emptyset = \emptyset$ 

In [77]:
A = np.array([
        [43, 75, 33], 
        [45, 55, 66], 
        [17, 68, 89]
        ])
B = np.array([
        [1,0,0], 
        [0,1,0],
        [0,0,1]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print(result)

[[43, 75, 33], [45, 55, 66], [17, 68, 89]]


## Conclusion

Python is a well-known and popular programming language that is in great demand throughout the globe. It is applicable to a variety of fields, including data science, big data, programming, and application development. The students were able to practice and comprehend the concepts, syntax, and techniques of Python by completing this laboratory report. It entails familiarity with matrices and their relationship to linear equations, the ability to perform fundamental matrix operations, and the ability to program/translate matrix equations and operations. Learning the fundamentals undoubtedly aided in the acquisition of a load of new and useful characteristics. It will assist you in thinking more logically. You will be able to grasp complex ideas more easily and solve problems more effectively as a result of this course. 

At the end of the module, the students became capable of applying the knowledge about the language by involving themselves in doing several practices such as creating a corresponding matrix representing a linear combination, encoding and describing it as a matrix, expressing it as a linear combination, and Matrix Operations which includes Transposition, Dot Product/Inner Product and it’s rules, Determinant, and Inverse.  On the other hand, a task was performed. The program begins by being familiar with transposition, dot product, determinant and inverse. This familiarization aids us in putting our newfound knowledge into practice by allowing us to construct matrices that deal with multiplication properties. Moreover, a flow chart was created in relation to the tasks that discussed the methods and functions used. Furthermore, learning the fundamentals of programming helps develop mental abilities that are extremely useful in a variety of other areas of life. This engagement could assist people to make key patient care decisions and help us make huge changes. We'd look at the matrices first, then learn about each quality outcome and how competencies, abilities, and other aspects affect it. This setting would assist users to make vital patient care decisions. These matrices would also be useful for health care training, allowing us to broaden the scope of research and benefit the health care system. The ability to deconstruct a large problem into a series of increasingly small tasks, to abstract a solution in order to make it applicable to a larger set of problems, and even to develop fluency in logical analysis through debugging are all developmental skills that aid in decision making and critical thinking, which are necessary for solving healthcare problems.