<a href="https://colab.research.google.com/github/phospeyt/Linear-Algebra_Second-Sem/blob/main/POLICARPIO_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4: Matrices 

Now that you have a fundamental knowlege about Python, well try to look into greater dimensions. 

##Objectives

At the end of this activity you will be able to:

  1. Be familiar with matrices and their relation to linear equations.
  2. Perform basic matrix operations.
  3. Program and translate matrix equations and operations using Python.



##Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are the also handy representations of complex equations or multiple inter-related equations from 2- dimensional equations to even hundreds and thousands of them,

Let's say for example you have A and B as a system of equation. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C= \left\{
   \begin{array}\
      w-2x+3y-4z \\
      3w- x -2y +z \\
      2w -x +3y - 2z
    \end{array}
\right. $$

We could see that  is a system of 2 equations with 2 parameters. While  is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end
{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called
the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices.
And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented
just like the equation below. Whereas A is a matrix consisting of elements denoted by Qi g. Denoted by i is the number of rows in the matrix
while j stands for the number of columns.
Do note that the size of a matrix is i x j.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.



In [ ]:
## Since we'll keep on descriibing matrices, Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2x2 matrix
F = np.array([
    [2, 3],
    [5, 4]
])
describe_mat(F)

Matrix:
[[2 3]
 [5 4]]

Shape:	(2, 2)
Rank:	2



In [ ]:
N = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(N)


Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
A = np.array([
    [2, 3],
    [5, 4],
    [3,3]
])
describe_mat(A)

Matrix:
[[2 3]
 [5 4]
 [3 3]]

Shape:	(3, 2)
Rank:	2



In [ ]:
O = np.array([8,7,6,5,4])
describe_mat(O)

Matrix:
[8 7 6 5 4]

Shape:	(5,)
Rank:	1



#Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.





##**According** **to** **shape**

Row and Column Matrices

In vector and matrix computations, row and column matrices are frequently used. Additionally, they can be used to represent the row and column spaces of a larger vector space. Single column or single row matrices are used to depict row and column matrices. Thus, row matrices have the shape I x j, while column matrices have the shape I x l.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 2, 3, 4
]) ## this is a 1-D Matrix with a shape of (4,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,4)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [2],
    [4],
    [6],
    [8]
]) ## This is a 2-D Matrix with a shape of (4,1)
describe_mat(col_mat)


Matrix:
[[2]
 [4]
 [6]
 [8]]

Shape:	(4, 1)
Rank:	2



Square Matrix

Square matrices have the same row and column dimensions. We could say that a matrix is square if and only if. To determine square matrices, we can tweak our matrix descriptor function.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.Shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
  [1,2,6],
  [4,8,12],
  [6,12,18]
])

non_square_mat = np.array([
  [3,2,1],
  [4,3,2]                
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 1  2  6]
 [ 4  8 12]
 [ 6 12 18]]

Shape:	(3, 3)
Rank:	2

Matrix:
[[3 2 1]
 [4 3 2]]

Shape:	(2, 3)
Rank:	2



## **According to Element Values**

##### Null Matrix

A Null Matrix is an empty matrix. It is always a subspace of a vector or matrix of any dimension.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrux.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat= np.array([])
describe_mat(null_mat)

Matrix is Null


 Zero Matrix

Zero matrix is a matrix with any dimensions in which all of its element entries are zeros.

In [ ]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((2,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectamgular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectamgular Matrix: 
[[0. 0.]
 [0. 0.]]


Ones matrix

A matrix of ones is a matrix in mathematics in which each element is equal to one. The following are some examples of standard notation: In some instances, the term "unit matrix" is used interchangeably with "matrix of ones."


In [ ]:
ones_mat_row = np.ones ((1,2))
ones_mat_sqr = np.ones ((2,2))
ones_mat_rct = np.ones ((2,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectamgular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectamgular Matrix: 
[[1. 1.]
 [1. 1.]]


Diagonal Matrix

A diagonal matrix contains both upper and lower triangular elements. i.e., every element above and below the principal diagonal is a zero.

In [ ]:
np.array([
   [2,0,0],
   [0,3,0],
   [0,0,5]
])
# a[1,1], a[2,2], [3,3], ...a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,4,6,8])
d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

Identity Matrix

The Identity Matrix is a nxn square matrix with a diagonal of ones and all other elements being zeros. Additionally, it is referred to as a Unit Matrix or Elementary matrix. It is denoted by the symbol In or simply by I, where n denotes the size of the square matrix.

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
  [1,2,3,4],
  [0,4,6,8],
  [0,0,9,12],
  [0,0,0,16]
])

array([[ 1,  2,  3,  4],
       [ 0,  4,  6,  8],
       [ 0,  0,  9, 12],
       [ 0,  0,  0, 16]])

Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.


##Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


$$
\theta=\begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

2.Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0]== matrix.shape[1] else False
  print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
A = np.array([
    [1,2,1],
    [0,4,-1],
    [0,0,10]
])
describe_mat(A)

matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown





In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{
    \begin{array}\
        x + 7y + 8z \\ 
        2x + 2y + 2z \\
        4x + 6y + 7z
    \end{array}
\right. $$

$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H =\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
        x \\ 
        2x + 2x \\
        4x + 6y + 7z
    \end{array}
\right. $$

# **Matrix Algebra**

Addition

In [ ]:
A= np.array([
    [1,2],
    [2,3],
    [4,1]       
])
B= np.array([
    [6,2],
    [4,3],
    [4,5]          
])
A+B

array([[7, 4],
       [6, 6],
       [8, 6]])

In [ ]:
3+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[4, 5],
       [5, 6],
       [7, 4]])

Subtraction

In [ ]:
A-B

array([[-5,  0],
       [-2,  0],
       [ 0, -4]])

In [ ]:
3-B

array([[-3,  1],
       [-1,  0],
       [-1, -2]])

Element Wise Multiplication

In [ ]:
A*B

array([[ 6,  4],
       [ 8,  9],
       [16,  5]])

In [ ]:
2*L

array([[2, 4],
       [4, 6],
       [8, 2]])

In [ ]:
A = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

B = np.array([
    [5,7,8],
    [2,6,2],
    [2,6,8]
])

A@B

array([[ 35,  97,  86],
       [ 18,  38,  36],
       [ 46, 106, 100]])

In [ ]:
F = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

In [ ]:
alpha=10**-10
F/(alpha+F)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.add(L,F)


array([[ 6, 14, 16],
       [ 4,  8,  4],
       [ 6, 12, 15]])

# **Activity**

**Task 1**
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 3 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_desc(G)

[[1 7 8]
 [2 2 2]
 [4 6 7]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
G = np.array([
    [0,1,4,8],
    [3,5,7,9],
    [2,6,4,8]
])

mat_desc(G)

[[0 1 4 8]
 [3 5 7 9]
 [2 6 4 8]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
G = np.array([
    [0,6,7,2],
    [3,5,8,4],
    [2,3,4,9],
    [0,4,3,2]
])

mat_desc(G)

[[0 6 7 2]
 [3 5 8 4]
 [2 3 4 9]
 [0 4 3 2]]
Shape: (4, 4)
Size: 16
Rank: 4
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
G = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
])

mat_desc(G)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (4, 4)
Size: 16
Rank: 0
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is an zeros matrix


**Task 2**
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The shape of both matrices are not same. Could not perform operations.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the given matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the given matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)


In [ ]:
mat1 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat2 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_operations(mat1, mat2)

Matrix 1: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Matrix 2: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Sum of the given matrices:
[[ 2 14 16]
 [ 4  4  4]
 [ 8 12 14]]
Difference of the given matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-wise multiplication of the given matrices:
[[ 1 49 64]
 [ 4  4  4]
 [16 36 49]]
Element-wise division of the given matrices:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
mat1 = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

mat2 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_operations(mat1, mat2)

Matrix 1: [[0 0 0]
 [0 0 0]
 [0 0 0]]
Matrix 2: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Sum of the given matrices:
[[1 7 8]
 [2 2 2]
 [4 6 7]]
Difference of the given matrices:
[[-1 -7 -8]
 [-2 -2 -2]
 [-4 -6 -7]]
Element-wise multiplication of the given matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-wise division of the given matrices:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
mat1 = np.array([
    [0,0,0],
    [2,2,2],
    [4,4,4]
])

mat2 = np.array([
    [1,2,3],
    [0,0,0],
    [4,5,6]
])

mat_operations(mat1, mat2)

Matrix 1: [[0 0 0]
 [2 2 2]
 [4 4 4]]
Matrix 2: [[1 2 3]
 [0 0 0]
 [4 5 6]]
Sum of the given matrices:
[[ 1  2  3]
 [ 2  2  2]
 [ 8  9 10]]
Difference of the given matrices:
[[-1 -2 -3]
 [ 2  2  2]
 [ 0 -1 -2]]
Element-wise multiplication of the given matrices:
[[ 0  0  0]
 [ 0  0  0]
 [16 20 24]]
Element-wise division of the given matrices:
[[0.         0.         0.        ]
 [       inf        inf        inf]
 [1.         0.8        0.66666667]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


In [ ]:
mat1 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat2 = np.array([
    [9,3,8,6],
    [2,0,9,3],
    [5,7,2,1]
])

mat_operations(mat1, mat2)

Matrix 1: [[1 7 8]
 [2 2 2]
 [4 6 7]]
Matrix 2: [[9 3 8 6]
 [2 0 9 3]
 [5 7 2 1]]
The shape of both matrices are not same. Could not perform operations.


#**Conclusion**

  Python is a well-known and popular programming language that is in great demand throughout the globe. It is applicable to a variety of fields, including data science, big data, programming, and application development. The students were able to practice and comprehend the concepts, syntax, and techniques of Python by completing this laboratory report. It entails familiarity with matrices and their relationship to linear equations, the ability to perform fundamental matrix operations, and the ability to program/translate matrix equations and operations. Learning the fundamentals undoubtedly aided in the acquisition of a load of new and useful characteristics. It will assist you in thinking more logically. You will be able to grasp complex ideas more easily and solve problems more effectively as a result of this course. 

  At the end of the module, the students became capable of applying the knowledge about the language by involving themselves in doing several practices such as creating a corresponding matrix representing a linear combination, encoding and describing it as a matrix, and expressing it as a linear combination in a markdown and a LaTeX markdown. On the other hand, two tasks were performed. The program begins by creating a function named mat desc() that comprehensively describes a matrix by displaying its shape, size, and rank, indicating whether the matrix is square or non-square, indicating whether the matrix is empty, and indicating whether the matrix is an identity, ones, or zeros matrix. The second task is to create a function named mat operations() that accepts two matrices as input parameters. It determines whether the matrices are viable for operation and returns your own error message if they are not, and it returns the matrices' sum, difference, element-wise multiplication, and element-wise division. Two flow charts were created in relation to the tasks that discussed the methods and functions used. Furthermore, learning the fundamentals of programming helps develop mental abilities that are extremely useful in a variety of other areas of life. The ability to deconstruct a large problem into a series of increasingly small tasks, to abstract a solution in order to make it applicable to a larger set of problems, and even to develop fluency in logical analysis through debugging are all developmental skills that aid in decision making and critical thinking, which are necessary for solving technology problems.
